### PR TITLE
lxc.md: update to support correct arch on voidlinux templates

### PR DESCRIPTION
**Pull request by brdelphus**
Before submitting a pull request, please read [CONTRIBUTING](./CONTRIBUTING.md); pull requests that do not meet the criteria described there will not be merged. Note that this repository's CONTRIBUTING contains information specific to this repository, and is not the same as CONTRIBUTING for the void-packages repository.

We prioritise pull requests involving information specific to Void over those involving information applicable to Linux in general.

### CODE REVIEW

**Comment by Vaelatern** [comment]
Excuse me?

**Comment by Vaelatern** [comment]
I can remove this if you explain why this PR is at all relevant or useful

**Comment by brdelphus** [comment]
void linux lxc handbook presents the line:  lxc-create -n mycontainer -t download -- \
	--dist voidlinux --release current --arch x86_64
while in reality, there is no x86_64 in lxc downloads but amd64 only as it shows bellow:
voidlinux	current	amd64	default	20201021_17:10
voidlinux	current	arm64	default	20201021_17:10
voidlinux	current	armhf	default	20201021_17:10
voidlinux	current	i386	default	20201021_17:10

so the example command handbook presents would never work if not replaced to amd64

**Comment by Vaelatern** [comment]
That's a problem, but it might be best to fix lxc rather than these docs, since void consistently uses `x86_64` in reference to the amd64 instruction set.

**Comment by brdelphus** [comment]
Its the way lxc templates are presented there. I believe we can't change it. see ubuntu examples bellow:
ubuntu	groovy	amd64	default	20201021_07:42
ubuntu	groovy	arm64	default	20201021_07:42
ubuntu	groovy	armhf	default	20201021_07:42
ubuntu	groovy	ppc64el	default	20201021_08:00
ubuntu	groovy	s390x	default	20201021_07:42
ubuntu	trusty	amd64	default	20201021_07:42
ubuntu	trusty	arm64	default	20201021_07:42
ubuntu	trusty	armhf	default	20201021_07:42
ubuntu	trusty	i386	default	20201021_07:42
ubuntu	trusty	ppc64el	default	20201021_07:42
ubuntu	xenial	amd64	default	20201021_07:42
ubuntu	xenial	arm64	default	20201021_07:42
ubuntu	xenial	armhf	default	20201021_07:42
ubuntu	xenial	i386	default	20201021_07:42
ubuntu	xenial	ppc64el	default	20201021_07:59
ubuntu	xenial	s390x	default	20201021_07:42
voidlinux	current	amd64	default	20201021_17:10
voidlinux	current	arm64	default	20201021_17:10
voidlinux	current	armhf	default	20201021_17:10
voidlinux	current	i386	default	20201021_17:10

So to my understanding, whoever wrote lxc handbook, did not understand the way lxc display their options, as amd64 images work as x86_64. 
[root@insight delphus]# uname -a
Linux insight 5.8.16_1 #1 SMP Sat Oct 17 12:21:35 UTC 2020 x86_64 GNU/Linux
[root@insight delphus]# lxc-attach -n pihole
root@pihole:/# uname -a
Linux pihole 5.8.16_1 #1 SMP Sat Oct 17 12:21:35 UTC 2020 x86_64 GNU/Linux
root@pihole:/# exit
that pihole container runs lxc debian image as amd64

**Comment by brdelphus** [comment]
either this is just a typo in handbook, or a misinterpretation of how lxc images are presented in lxc image download template.

**Comment by brdelphus** [comment]
but I agree with you, there it should be mentioned that lxc amd64 images are like x86_64 for regular distro kernels. anyways just happy to bring it to attention, and nevertheless trying to contribute not just opening another issue.

**Comment by ericonr** [comment]
@brdelphus thank you, merged! You forgot to fix the paragraph below, so I edited that as well.

Interestingly, LXC does support `x86_64` as an architecture name, it just isn't used by anybody :P 

https://github.com/lxc/lxc/blob/708e0653c859914b41cdfa091c599f31dd003a61/src/lxc/confile.c#L2993

**Pull request closed without merging**
