### PR TITLE
Create iptables.md

### PR DESCRIPTION
**Pull request by fabulvoid**
Describes how to activate the iptables firewall.

### CODE REVIEW

**Comment by Duncaen** [comment]
I think the runit services for iptables are bad and shouldn't be promoted.
All runit services start in parallel, your web service might start before the iptables rules are loaded.

**Comment by Vaelatern** [comment]
The alternative is a line in `rc.local` which is the correct course.

**Comment by fabulvoid** [comment]
Thanks for your feedback. I have edited 'iptables.md' according to @Vaelatern's suggestion. Hope my contribution is more usable now.

**Comment by Piraty** [comment]
Void also ships `runit-iptables` for a few month now, which restore iptables during stage1 (core-services). If this can be considered elegant is up to debate, but at least they are activated before network is up...

**Comment by bobertlo** [comment]
@Piraty that looks interesting.

@fabulvoid please rebase this branch into a single commit.

**Comment by bobertlo** [comment]
@Duncaen @Vaelatern does the `runit-iptables` package seem like a better solution to this? It looks clean to me and I think it would be simpler to mention that package and, maybe, also mention `rc.local` as an alternative? It's not a big difference either way, I'd just like opinions.

**Comment by bobertlo** [comment]
Closed by https://github.com/void-linux/void-docs/commit/aa9a6ad2ce51a656866e2868ad2c12cf16d2728c

**Pull request closed without merging**
