### PR TITLE
post-install,guide: Multiple changes.

### PR DESCRIPTION
**Pull request by flexibeast**
Addresses #268.

### CODE REVIEW

**Comment by ericonr** [comment]
Technically speaking, a chroot installation using a ROOTFS image also requires an update. It probably makes more sense to include that in the advanced guide, though.

**Comment by flexibeast** [comment]
@ericonr: Good point. How about just "After completing installation, be sure ..."?

**Comment by ericonr** [comment]
I like the way you wrote, because "completing installation" might end up with someone updating the live system :p . I'd leave it as is.

**Comment by flexibeast** [comment]
Ah okay. Well, if there's nothing else, would you be able to merge this, please?

**Pull request merged**
