### PR TITLE
Steam doc

### PR DESCRIPTION
**Pull request by Frick-David**
Can someone provide some feedback on if this will mess up my docker-doc. I was using git from the terminal (something I typically do not do), and I forgot to branch for steam so I still had docker in there. I had to amend the commit. Just hoping to keep things flowing.

### CODE REVIEW

**Comment by Frick-David** [comment]
Oh no, I do see that nasty docker commit. HMMMM, is there a way to drop that commit since it is from my docker branch and not steam on the command-line. :( :( :(

**Comment by Vaelatern** [comment]
`git rebase -i @~4; git rebase master`

**Comment by Frick-David** [comment]
@Vaelatern Would I need to do anything after or just rerun the commands to force push it?
`git add ...`
`git commit --amend`
`git push -force`

**Comment by Vaelatern** [comment]
Just that and force push

**Comment by Frick-David** [comment]
`git rebase -i @~4; git rebase master` and then `git push --force` results in a message:
```
git push --force
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

```

because I am now not on steam-doc branch but rather 
```
git branch

* (no branch, rebasing steam-doc)
  docker-doc
  master
  steam-doc
```
I am not entirely sure that is what I want. But maybe I am wrong

**Comment by Vaelatern** [comment]
Your rebase is not done yet, `git status` might help

**Comment by aeosynth** [comment]
Might be helpful to mention that steam can be installed with flatpak.

**Comment by Frick-David** [comment]
Going to Fix this up including information about flatpak and open another PR since I fear messing this up to much.

**Pull request closed without merging**
