### PR TITLE
locales: Add section.

### PR DESCRIPTION
**Pull request by flexibeast**

### CODE REVIEW

**Comment by ericonr** [comment]
What do you think about mentioning `/etc/locale.conf`, as well? It's where the actual locale is selected.

**Comment by flexibeast** [comment]
@ericonr: Good suggestion, thanks! PR updated.

**Comment by bobertlo** [comment]
I think a layout like the following might be more helpful:

# Locales

For a list of currently enabled locales run:

```
locale -a
```
## Enabling locales

To enable the locale `xxxx` un-comment or add the proper line in `/etc/default/libc-locale.conf` and run

```
# xbps-reconfigure -f glibc-locales
```

## Setting the System locale

Then set `LANG=xxxx` in `/etc/locale.conf`

**Comment by flexibeast** [comment]
@bobertlo: Thanks, updated.

**Pull request merged**
