### PR TITLE
about-handbook/index, style-guide: Add text about placeholders.

### PR DESCRIPTION
**Pull request by flexibeast**
This PR is based on extant usage patterns in the Handbook.

### CODE REVIEW

**Comment by hippi777** [comment]
hi there! :)

what about "$whatever" for placeholders instead of "<whatever>"? its better for copypaste codes and its more natural...

**Comment by abenson** [comment]
Using `<placeholder>` is fairly common in industry tech-writing.

**Comment by flexibeast** [comment]
@hippi777: Thank you for the suggestion, but no, for a few reasons:

* Given that many commands are intended to be run from a shell, `$whatever` looks much more like something that should be typed literally, compared to `<whatever>`.

* As [the style guide](https://docs.voidlinux.org/contributing/void-docs/style-guide.html) notes:

> Outside of the 'installation' sections, step-by-step instructions containing 'magic' commands for copying-and-pasting are strongly discouraged. Users are expected to read the canonical documentation (e.g. man pages) for individual programs to understand how to use them, rather than relying on copying-and-pasting.

* `<whatever>` is the most commonly-used format currently used in the Handbook, and i feel there's no sufficiently strong reason to get into bikeshedding an alternative, so it's enough to codify existing practice to ensure consistency of style.

**Comment by hippi777** [comment]
fine, it was only an idea :D

**Pull request merged**
