### PR TITLE
gnome: Modify example for testing that `gdm` works.

### PR DESCRIPTION
**Pull request by flexibeast**
As recommended by @Duncaen [here](https://github.com/void-linux/void-docs/pull/249#issuecomment-625428886).

### CODE REVIEW

**Comment by ericonr** [comment]
I'd prefer to have this in a single section under `services/`, and link to that. Perhaps mention that if they disable the service they should remove the `down` file as well? Otherwise they might forget it when trying to enable the service again.

**Comment by flexibeast** [comment]
@ericonr: So make creation of such a new section a blocker for #237?

**Comment by ericonr** [comment]
If you're up to writing it, I don't have an issue with it being included in that PR. If not, then yes, a blocker. I can try to get to it, if you can't.

**Comment by flexibeast** [comment]
Sure, i'll see what i can do. :-)

**Comment by ericonr** [comment]
@flexibeast perhaps even merge this PR into that one? That way the change comes in one piece.

**Comment by ericonr** [comment]
So this one can just become a link to that page, right?

**Pull request merged**
