### PR TITLE
cups: add how-to setup service

### PR DESCRIPTION
**Pull request by go2null**

### CODE REVIEW

**Comment by CameronNemo** [comment]
https://github.com/void-linux/void-docs/blob/master/src/config/print/config.md

**Comment by go2null** [comment]
hmm.
Should the `install#Configuration software` section be merged into the `config` file?

**Comment by bobertlo** [comment]
@go2null are you still interested in this? see #41

**Comment by bobertlo** [comment]
Closing, because #64 deprecates this

**Pull request closed without merging**
