### PR TITLE
new page: config/network/connman

### PR DESCRIPTION
**Pull request by lugubris**

### CODE REVIEW

**Comment by Duncaen** [comment]
I changed the connmand service to source the `conf` file like most services do.
Can you change the last section to something like:

> create `/etc/sv/connmand/conf` with the following content
> ```
> OPTS="--nodnsproxy"
> ```

**Comment by lugubris** [comment]
Duncan Overbruck @ 2019-09-06 15:04 UTC:

> I changed the connmand service to source the `conf` file like most services do.
> Can you change the last section to something like:
>
>> create `/etc/sv/connmand/conf` with the following content
>> ```
>> OPTS="--nodnsproxy"
>> ```

resolved

--
                                Lugubris

**Comment by Duncaen** [comment]
Just needs a link in `SUMMARY.md` then it looks ready to me.

**Comment by lugubris** [comment]
Duncan Overbruck @ 2019-09-06 15:23 UTC:

> Just needs a link in SUMMARY.md then it looks ready to me.

resolved. I accidently commited to my master which looks messed up now
because of `git commit --amend` but thankfully we can revert that [0].

[0] -> https://stackoverflow.com/questions/1459150/how-to-undo-git-commit-amend-done-instead-of-git-commit

--
                                Lugubris

**Pull request merged**
