### PR TITLE
power-management: acpid is not always enabled.

### PR DESCRIPTION
**Pull request by ericonr**
Not sure this is the best way to phrase it, just wanted to get started on it.

### CODE REVIEW

**Comment by flexibeast** [comment]
Is it only enabled by default when installing from an ISO, or are there other cases as well? (Or does whether or not it's enabled depend on the flavour as well?)

**Comment by ericonr** [comment]
I actually don't know :p 

I can try to take a look at how mklive is configured for this, but I'm not sure we should try to list where it happens and where it doesn't.

**Comment by ericonr** [comment]
Updated.

**Comment by flexibeast** [comment]
LGTM.

**Comment by ericonr** [comment]
Thanks!

**Pull request merged**
