### PR TITLE
src/xbps/repositories/mirrors/index.md: Add more mirror links.

### PR DESCRIPTION
**Pull request by Prince213**
Closes #339.

### CODE REVIEW

**Comment by ericonr** [comment]
Huh, I didn't know we had that many. How did you collect them? Thanks, though! Would you mind adding the changes from #339 too?

**Comment by Prince213** [comment]
No, of course not. As for the sources... you may want to google `voidlinux mirror`.

**Comment by Prince213** [comment]
Also, should I sort entries in alphabetical order?

**Comment by ericonr** [comment]
> Also, should I sort entries in alphabetical order?

Yes, please.

>  As for the sources... you may want to google voidlinux mirror.

Lol, that makes sense :p 

Thanks for googling!

**Comment by Prince213** [comment]
> > Also, should I sort entries in alphabetical order?
> 
> Yes, please.

OK.

> > As for the sources... you may want to google voidlinux mirror.
> 
> Lol, that makes sense :p
> 
> Thanks for googling!

:D

**Comment by ericonr** [comment]
I've checked all the new mirrors, and they all seem to be reasonably up to date. Waiting for the ok from someone from @void-linux/void-ops to merge.

**Pull request merged**
