### PR TITLE
change to active voice

### PR DESCRIPTION
**Pull request by go2null**

### CODE REVIEW

**Comment by go2null** [comment]
Fix formatting per failed CI

**Comment by go2null** [comment]
weird error in CI:
`HEAD detached at d9c33e5`

**Comment by the-maldridge** [comment]
Its pretty clear your files are unformatted in that message.  Please format the files and push again.

**Comment by go2null** [comment]
took a while to figure out that `vmdfmt` was complaining about a missing blank line at the end of the file.

**Pull request merged**
