### PR TITLE
Update link to musl site, to reflect new domain.

### PR DESCRIPTION
**Pull request by flexibeast**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Other than the commit message, this looks good to me.
I don't know if there is anything wrong with the commit message.

**Comment by flexibeast** [comment]
@Vaelatern: Thanks for the review. :-) But, sorry, i don't understand your comment about the commit message; are you saying that others might find it confusing, or perhaps simply wrong in some sense?

**Comment by Vaelatern** [comment]
https://docs.voidlinux.org/contributing/void-docs/submitting.html

```
    The commit message should be in the form of section: what was changed
```

**Comment by flexibeast** [comment]
Ah, sorry about that! Commit message fixed.

**Comment by Vaelatern** [comment]
Sorry, should be: `about: update musl link to new domain`

**Comment by flexibeast** [comment]
Thanks, fixed. :-)

**Pull request merged**
