### PR TITLE
Update checkout

### PR DESCRIPTION
**Pull request by tiziodcaio**
Is a dumb update... I only suggest it no worries... 😉

### CODE REVIEW

**Comment by abenson** [comment]
Change the commit message to be a little more explanatory.

**Comment by ericonr** [comment]
I'm letting it run, but pretty sure v2 doesn't work because it uses glibc linked nodejs.

**Comment by ericonr** [comment]
```
  /usr/bin/docker exec  3e41505112e32180bbbf07d26432ab8c194f0d3ad9599e8d0bb55b04725e586d sh -c "cat /etc/*release | grep ^ID"
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: no such file or directory: unknown
```

or it fails even early D:

**Comment by tiziodcaio** [comment]
> I'm letting it run, but pretty sure v2 doesn't work because it uses glibc linked nodejs.

Ok sure, I will close the pull if is it

**Pull request closed without merging**
