### PR TITLE
Update void naming explaination.

### PR DESCRIPTION
**Pull request by lemmi**
Should we really pass up an opportunity like that?

### CODE REVIEW

**Comment by flexibeast** [comment]
Hah! Nice. :-) What do people think?

**Comment by ericonr** [comment]
I am 125% in favor.

**Comment by abenson** [comment]
Perfect!

**Comment by bobertlo** [comment]
I thought Xtraeme mentioned on irc part of the name choice void had to do with being able to bootstrap from nothing? I don't have any other sources and maybe other people know better than me the origin. I'm assuming someone with the project much longer than I provided a source on this?

**Comment by flexibeast** [comment]
@bobertlo: My [source](https://wiki.voidlinux.org/Frequently_Asked_Questions#Void_Linux_name_origin) for that was the FAQ on the old wiki. But that references a post on forum.voidlinux.org which doesn't appear to be available via the Wayback Machine. :-(

**Comment by Vaelatern** [comment]
I'd rather `devoid of meaning` personally.

**Comment by ahesford** [comment]
Saw the branch but not this PR. I originally thought "void of any meaning" sounded ill formed, but there is precedent. Looks good to me.

**Pull request merged**
