### PR TITLE
theme/css/general.css: use dark theme if prefered

### PR DESCRIPTION
**Pull request by PaperMountainStudio**
This PR uses the new prefers-color-scheme media query to determine if user's OS is set to dark mode (or browser is manually set to dark mode) and uses dark theme.

Let me know if I should improve something.

### CODE REVIEW

**Comment by Vaelatern** [comment]
Cool, I think we should merge as-is unless someone has a substantive issue.

**Comment by ericonr** [comment]
@Vaelatern have you tested it locally? I don't use dark mode too much so I don't have any stakes on this. It looks reasonable for me, and could make life better for those who do use dark mode in other places.

**Comment by PaperMountainStudio** [comment]
I am not sure about 2 things:
1) is the background dark enough? I have seen pages looking like this, but I am not sure if other people will find it sufficient.
2) I am not sure about the blockquote design, it seems a little bit out of place. This is the best I came up with though.

If someone is a designer, I will be happy to change the colors.

**Comment by ericonr** [comment]
For blockquote, did you consider any other color? I have to agree, the green looks somewhat weird. I'm trying to think of some color that would be compatible with the current style.

**Comment by PaperMountainStudio** [comment]
I tried using the color which is already in the light theme, but making it lighter or darker. I think you are talking about the code blocks though. That's one more thing I am not happy with. Blockquote is the light grey rectangle.

**Comment by ericonr** [comment]
Yes, sorry! The blockquotes look good to me, I think the issue is with how it matches the code block inside it.

**Comment by PaperMountainStudio** [comment]
preview2:

**Comment by jeffayle** [comment]
The two boxes on the page are a blockquote and a pre---I don't think those two elements should be styled so similarly. I think there should also be some way to identify <code> visually other than the monospaced font.

**Comment by Vaelatern** [comment]
tweak: can you please make the header bar color darker? Closer to the code block color. When using dark mode I do like when the website is actually dark.

**Comment by PaperMountainStudio** [comment]
preview3:
preview 3

@Vaelatern I made all the colors a bit darker. I don't want to go with even darker color for the nav bar, because it would not fit in the original colorscheme. Do you think this is enough?

**Comment by ericonr** [comment]
I like this last version! @Vaelatern can you give it a last look, please?

**Comment by hippi777** [comment]
hi folks! :) its really neat, but how can i check it out in action?!!! :D thx!

**Comment by ericonr** [comment]
@hippi777 you have to clone this repository, install `mdBook` and run `mdbook serve` inside it. It will tell you what you need to open in your browser to access this (I believe it's `localhost:3000`).

**Comment by hippi777** [comment]
ahh, thx 4 ur effort, but actually i couldnt figure out where the switch was hidden on the docs.void pages and i only wanted that... :D will it be there, or this will be the only way?

**Comment by PaperMountainStudio** [comment]
A switch is not something I personally need, but I might work on it in
the near future. Currently, your browser has to be set to dark mode, if
you are using firefox, use this:
1. Go to about:config
2. Add a new variable ui.systemUsesDarkTheme of type number with value 1

And all pages supporting this media query will change to dark. I think 
firefox will make this accessible from the settings in next versions or
they will read if the OS is set to dark on Linux (they do on Mac and
Windows).

**Comment by hippi777** [comment]
WOW THX!!!! :D

**Comment by ericonr** [comment]
@flexibeast can this be merged? Or should it go in the `book.css` file you mentioned in #298 ?

**Comment by flexibeast** [comment]
@ericonr: No, i don't think that needs to be a blocker here. i'll open a separate issue for that shortly, and merge this PR now.

**Comment by ericonr** [comment]
Cool! Thanks @PaperMountainStudio !

**Pull request merged**
