### PR TITLE
 wpa_supplicant: document new DRIVER option 

### PR DESCRIPTION
**Pull request by matthias-t**
https://github.com/void-linux/void-packages/pull/20972

### CODE REVIEW

**Comment by matthias-t** [comment]
If you pass only `-D <driver>` to `OPTS`, then no interface or configuration file is specified, as `OPTS` overrides all other options. This confused me when setting up `wpa_supplicant`. But it's true that one can set `-i` and `-c` there as well.

**Comment by bobertlo** [comment]
Oh, missed that. Fair enough!

**Comment by bobertlo** [comment]
d98fabccb4446b924680eda82c855ec4bba8afe2

**Comment by bobertlo** [comment]
Thanks. Please be sure to squash commits in the future :)

**Comment by matthias-t** [comment]
Okay, sure! I'll try to get the formatting right, too

**Pull request closed without merging**
