### PR TITLE
kde: add dbus dep for sddm.

### PR DESCRIPTION
**Pull request by ericonr**
@flexibeast does this line up with your experiments?

We had someone on reddit need to enable dbus in order to get SDDM working.

### CODE REVIEW

**Comment by flexibeast** [comment]
TLA;DR - Too Long Ago; Don't Remember. :-) Would you like me to create a VM to test?

**Comment by ericonr** [comment]
Hmm if it's easy for you to, sure. Otherwise, maldridge confirmed it on IRC so I would be ok with merging since you don't remember it for sure.

**Comment by flexibeast** [comment]
i think if maldridge has confirmed it, that's probably sufficient. :-)

**Comment by ericonr** [comment]
Thanks!

**Pull request merged**
