### PR TITLE
history/index,xorg: Remove unneeded `/`, add final newline.

### PR DESCRIPTION
**Pull request by flexibeast**

### CODE REVIEW

**Comment by ericonr** [comment]
AFAIK vmdfmt doesn't allow for empty newlines

**Comment by flexibeast** [comment]
Ah. That will mean making `mdbook-latex` a bit more complicated, but okay. Thanks for the heads-up.

**Comment by bobertlo** [comment]
I originally had a trailing newline but people didn't like it. A single stable output for version control is sort of the point :)

**Comment by flexibeast** [comment]
@bobertlo: i.e. make sure there's never a trailing newline, rather than possibly having to insert one to keep everything consistent? If so, fair enough. :-)

**Comment by bobertlo** [comment]
Yes. There are commits adding a newline to every file and then removing it lol.

Any valid markdown with the same content should produce the same output byte for byte.

**Pull request merged**
