### PR TITLE
common-errors: Expand section.

### PR DESCRIPTION
**Pull request by flexibeast**
* Mention "Operation not permitted" errors.
* Mention "Not Found" errors.

This PR addresses #89. Need to confirm that the error produced by incorrect system time is "Operation not permitted".

### CODE REVIEW

**Comment by ericonr** [comment]
```
[*] Updating repository `https://mirror.clarkson.edu/voidlinux/current/musl/x86_64-musl-repodata' ...
Certificate verification failed for /CN=mirror.clarkson.edu
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://mirror.clarkson.edu/voidlinux/current/musl/x86_64-musl-repodata': Operation not permitted
Certificate verification failed for /CN=mirror.clarkson.edu
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://mirror.clarkson.edu/voidlinux/current/musl/nonfree/x86_64-musl-repodata': Operation not permitted
Certificate verification failed for /CN=mirror.clarkson.edu
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://mirror.clarkson.edu/voidlinux/current/musl/debug/x86_64-musl-repodata': Operation not permitted
Certificate verification failed for /CN=a-hel-fi.m.voidlinux.org
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/musl/nonfree/x86_64-musl-repodata': Operation not permitted
Certificate verification failed for /CN=a-hel-fi.m.voidlinux.org
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/musl/debug/x86_64-musl-repodata': Operation not permitted
[*] Updating repository `https://mirror.clarkson.edu/voidlinux/current/musl/nonfree/x86_64-musl-repodata' ...
[*] Updating repository `https://mirror.clarkson.edu/voidlinux/current/musl/debug/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/nonfree/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/debug/x86_64-musl-repodata' ...
```

confirmed

**Comment by flexibeast** [comment]
Great, thanks. Ok to merge?

**Comment by ericonr** [comment]
LGTM, thanks! I guess we can close #89 too?

**Comment by flexibeast** [comment]
Thanks, merged, and yep, just closed #89.

Nice trick with the clock. :-)

**Pull request merged**
