### PR TITLE
Add instructions for Installing the NVIDIA CUDA toolkit

### PR DESCRIPTION
**Pull request by chili-b**
There are some problems with the installer reporting missing ncurses libraries even if all the ncurses packages are installed. I couldn't find any writing about this anywhere else, so I wrote up the few things I did to make it work. Maybe this is the wrong place to put these notes, but I think they are helpful, so if that is the case please point me to a more appropriate place.

### CODE REVIEW

**Comment by flexibeast** [comment]
Thanks for your contribution!

@st3r4g, @ericonr: Thoughts on this?

**Comment by ericonr** [comment]
I was the one who suggested on IRC that they try to write something about this issue, that way we could discuss inclusion. On the one hand, it is useful info for users, and doesn't seem entirely too well documented. On the other hand, it might lead up to the external applications page being a big list of tricks for dealing with external stuff.I t isn't entirely bad, but it would be hard to maintain.

**Comment by flexibeast** [comment]
@ericonr: Well, info about CUDA is on [the list of wiki pages that possibly need inclusion in the Handbook](https://github.com/void-linux/void-docs/issues/327); i've mentioned this PR there. My thought is that CUDA content could accompany the other NVIDIA sections, rather than going in the "External Applications" section. (E.g. we could reorganise the existing NVIDIA sections to be under a general "NVIDIA" section, and CUDA content could go on the latter 'intro' page.)

**Comment by st3r4g** [comment]
why not packaging this instead?

**Comment by flexibeast** [comment]
@st3r4g: No reason - if this is something that can be addressed by packaging, then i'm all for it. :-)

**Pull request closed without merging**
