### PR TITLE
xbps/repositories/mirrors: add voidlinux.com.br/repo/

### LINKED ISSUE #653: Create Mirror
Hi! I want create a repository mirror in Brazil. We need.
But I saw that the size is around 1TB. I need ways (how to) how to reduce the size of the repository as much as possible. Unfortunately VPS in brazil is expensive

### PR DESCRIPTION
**Pull request by abdeoliveira**
Closes #653

### CODE REVIEW

**Comment by abdeoliveira** [comment]
I've made a little mess in positioning the entry in alphabetical order. The second commit fixed that.

**Comment by paper42** [comment]
Please open one PR and update it instead of closing it and opening a new one. This PR should contain only one commit, so please squash them.

**Comment by classabbyamp** [comment]
can you make the commit message "xbps/repositories/mirrors: add voidlinux.com.br/repo/"?

**Comment by abdeoliveira** [comment]
Sure. Just did it. :-)

**Pull request merged**
