### PR TITLE
Contribute build packages

### PR DESCRIPTION
**Pull request by felipevencato**
submitting.md: added reference to mdbook-linkcheck as a dependency to build the manual locally

### CODE REVIEW

**Comment by ericonr** [comment]
You accidentally left the commit from the other PR here :p 

And even though `mdbook build` complains about not finding `mdbook-linkcheck`, it still builds the entire book without issue. Do you think we could leave a note about that, instead?

**Comment by felipevencato** [comment]
I forgot about that commit. Still learning. Without mdbook-linkcheck it won't run mdbook serve.

**Comment by felipevencato** [comment]
Try to uninstall mdbook-linkcheck and run mdbook serve

**Comment by ericonr** [comment]
Oh, I had never tested this. Thanks for pointing it out.

I believe this is also a functionality bug for `mdbook`.

**Comment by felipevencato** [comment]
I was following your Contribute guide when I found this problem

**Comment by ericonr** [comment]
Reported: https://github.com/rust-lang/mdBook/issues/1283

**Comment by ericonr** [comment]
Do you know how to remove that commit from the other PR? You can probably just rebase your branch on upstream/master and it should go away from this PR. See https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

Regarding the change, you need to format it adequately, and I would instead mention that for _serving_ the handbook you need the `mdbook-linkcheck` package as well, since if you're _only_ building the handbook, it isn't needed.

**Comment by ericonr** [comment]
I believe this is new behavior, btw. They changed it for the latest release.

**Comment by felipevencato** [comment]
I will see what can I do

**Comment by ericonr** [comment]
Would you mind testing with my latest push? It should serve without issue now.

**Comment by felipevencato** [comment]
Sure. I will try!

**Comment by felipevencato** [comment]
Squashed

**Comment by felipevencato** [comment]
I uninstalled linkcheck and tried running mdbook serve and the result was the same... Error

**Comment by felipevencato** [comment]
It's weird. In Ubuntu mdbook serve gives me a completly diferent error.

"An error occured:
Indentation error on line:

   - [History](./about/history/index.md)"

**Comment by ericonr** [comment]
What is the `mdbook` version in ubuntu?

**Comment by felipevencato** [comment]
0.0.28

**Comment by felipevencato** [comment]
It gives the linkcheck erro on void and that other error on ubuntu

**Comment by ericonr** [comment]
The one in Void is `0.4.0`, so I really wouldn't expect the one in Ubuntu to work.

What I get with linkcheck not installed is:

```
$ mdbook serve
2020-07-26 00:42:33 [INFO] (mdbook::book): Book building has started
2020-07-26 00:42:33 [INFO] (mdbook::book): Running the html backend
2020-07-26 00:42:33 [INFO] (mdbook::book): Running the linkcheck backend
2020-07-26 00:42:33 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer
2020-07-26 00:42:33 [WARN] (mdbook::renderer): The command `mdbook-linkcheck` for backend `linkcheck` was not found, but was marked as optional.
2020-07-26 00:42:33 [INFO] (mdbook::cmd::serve): Serving on: http://localhost:3000
2020-07-26 00:42:33 [INFO] (warp::server): listening on http://[::1]:3000
2020-07-26 00:42:33 [INFO] (mdbook::cmd::watch): Listening for changes...
```

**Comment by felipevencato** [comment]
I get this
bash-5.0$ mdbook serve
2020-07-26 02:19:59 [INFO] (mdbook::book): Book building has started
2020-07-26 02:19:59 [INFO] (mdbook::book): Running the html backend
2020-07-26 02:20:02 [INFO] (mdbook::book): Running the linkcheck backend
2020-07-26 02:20:02 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer
2020-07-26 02:20:02 [ERROR] (mdbook::renderer): The command `mdbook-linkcheck` wasn't found, is the `linkcheck` backend installed?
2020-07-26 02:20:02 [ERROR] (mdbook::utils): Error: Rendering failed
2020-07-26 02:20:02 [ERROR] (mdbook::utils):    Caused By: Unable to start the backend
2020-07-26 02:20:02 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)

**Comment by felipevencato** [comment]
Why did you close this?

**Comment by ericonr** [comment]
I didn't close it: https://0x0.st/ix1y.png

Regarding that error, are you sure you have the latest version from this repo? I added an `optional = true` flag in the `book.toml` file, it should just ignore that it can't find `mdbook-linkcheck`.

**Comment by felipevencato** [comment]
This is the output from my terminal:

bash-5.0$ git checkout master && git pull && mdbook serve
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
2020-07-30 13:51:43 [INFO] (mdbook::book): Book building has started
2020-07-30 13:51:43 [INFO] (mdbook::book): Running the html backend
2020-07-30 13:51:46 [INFO] (mdbook::book): Running the linkcheck backend
2020-07-30 13:51:46 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer
2020-07-30 13:51:46 [ERROR] (mdbook::renderer): The command `mdbook-linkcheck` wasn't found, is the `linkcheck` backend installed?
2020-07-30 13:51:46 [ERROR] (mdbook::utils): Error: Rendering failed
2020-07-30 13:51:46 [ERROR] (mdbook::utils):    Caused By: Unable to start the backend
2020-07-30 13:51:46 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)

**Comment by ericonr** [comment]
If you're making changes here, isn't `origin` your own remote? I named the void-linux remote as `upstream`.

**Comment by ericonr** [comment]
Otherwise I really don't know what could be happening, since it seems to work cleanly for me and for @flexibeast, I think.

What's the output of `mdbook -V` ?

**Comment by felipevencato** [comment]
Just so you know. I'm using the musl version of void.

**Comment by felipevencato** [comment]
Checkmate!!! It was pointing to my fork. I recloned your repository and it works just fine. Thanks!
How is my repo diferent from yours and how can I fix this problem?

**Comment by ericonr** [comment]
https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

**Pull request closed without merging**
