### PR TITLE
management: Add reference to xbps.d(5) man page.

### PR DESCRIPTION
**Pull request by flexibeast**

### CODE REVIEW

**Comment by ericonr** [comment]
What do you think including a small item about each xbps-application? We have the list for "most general package management", then we add the more "specific" tools. Also mention xbps.d on that one.

That way I think we could close something like #113, perhaps.

**Comment by flexibeast** [comment]
@ericonr: i like that idea, especially since XBPS is a unique package manager that isn't (yet?) used and documented elsewhere; the Handbook seems like a good place to give a high-level overview of its components.

How would you feel about this PR being merged for now, and a separate issue/PR being opened for your suggestion?

Not sure i understand how your suggestion would help close #113 though .... Was that the actual issue number you meant?

**Comment by ericonr** [comment]
I think merging it is fine! And yes, I meant #103 :p

**Comment by flexibeast** [comment]
Thanks, merged. New issue opened as #235.

Ah! Yes, i see what you mean re. #103. :-)

**Pull request merged**
